### ISSUE TITLE
Hungary: name

### ISSUE THREAD

**Issue by KrzysztofMadejski** [emendelski/parldata-scrapers#1]
Priority: B
`name` should be divided into separate fields, apart from being saves as a whole:
- given_name
- additional_name
- family_name
- suffixes nad prefixes as mentioned in https://github.com/KohoVolit/api.parldata.eu/blob/master/schemas/person.py

**Comment by kubazarz** [comment]
Both website and API provide names in full form, that means "optional title + family name(s) + given name(s)". There's no rule to split name into separate parts.
Same thing with Montenegro.

**Comment by KrzysztofMadejski** [comment]
Optional titles can be easily filtered out [small closed dictionary] and put in honorix_prefix. 

Are family names hyphen connected? If so the name can be exploded by spaces and divided in proper fields.

**Comment by kubazarz** [comment]
Yes, titles are easy to extract.
Some of double family names are hyphen connected, but some aren't e.g. "Bangóné Borbély Ildikó" or "Slobodan Krušo Radović".
I'll try to split easy cases only.

**Comment by KrzysztofMadejski** [comment]
Note for future maintainers: create dictionary of hungarian given names and use it here.

**Comment by kubazarz** [comment]
Fixed with 28a0abb38df9a8e35d22bac7f352ee02f1cd50df

**Comment by KrzysztofMadejski** [comment]
OK
