### ISSUE TITLE
pl/sejm: speeches: events

### ISSUE THREAD

**Issue by KrzysztofMadejski** [emendelski/parldata-scrapers#6]
http://sejm.pl.sayit.parldata.eu/speeches

> All events are of type `sitting` with no parent, aren't there a structure of sessions consisting of several (usually one-day long) sittings in Polish Sejm? If so, there should be also `session` events referred by parent_id of the `sitting` events. Then a three-level section hierarchy is created in SayIt: parliament chambers for this election term (from organization referred in the events) -> sessions (from parent events of the sittings) -> sittings (from events referred by speeches).
- [x] http://api.mojepanstwo.pl/dane/dataset/sejm_posiedzenia/search.json should be mapped to `event type=session` instead of `sitting`
- [x] All sessions (posiedzenia) should have `organization_id = current chamber`
- [ ] http://api.mojepanstwo.pl/dane/dataset/sejm_posiedzenia_punkty/search.json should be mapped to events `type=sitting` with `organization_id = current chamber` and `parent_id = sejm_posiedzenia_punkty.posiedzenie_id`
- [ ] given speech (wystapienia) should be linked (`event_id`) to sitting `sejm_wystapienia.punkt_id` instead of session `sejm_wystapienia.posiedzenie_id`

**Comment by KrzysztofMadejski** [comment]
Puściłem scraper `scrapy crawl mojepanstwo.pl -s CLOSESPIDER_ERRORCOUNT=10 > /var/log/scrapers/pl/sejm.log
`, dostałem poniższy wynik, który interpretuję jako pozytywny:

```
        {'downloader/request_bytes': 29963711,
         'downloader/request_count': 85023,
         'downloader/request_method_count/GET': 85023,
         'downloader/response_bytes': 193315097,
         'downloader/response_count': 85023,
         'downloader/response_status_count/200': 85023,
         'dupefilter/filtered': 2278713,
         'finish_reason': 'finished',
         'finish_time': datetime.datetime(2015, 3, 23, 11, 3, 30, 138862),
         'item_dropped_count': 495,
         'item_dropped_reasons_count/DropItem': 495,
         'item_scraped_count': 2357862,
         'log_count/DEBUG': 2443967,
         'log_count/INFO': 83,
         'log_count/WARNING': 495,
         'request_depth_max': 788,
         'response_received_count': 85023,
         'scheduler/dequeued': 85023,
         'scheduler/dequeued/memory': 85023,
         'scheduler/enqueued': 85023,
         'scheduler/enqueued/memory': 85023,
         'start_time': datetime.datetime(2015, 3, 23, 9, 50, 16, 442882)}
```

Jednak w API nie ma żadnych sitting: http://api.parldata.eu/pl/sejm/events?where={%22type%22:%22sitting%22}

W speeches też pusto: http://api.parldata.eu/pl/sejm/speeches

**Comment by KrzysztofMadejski** [comment]
Jest grejt. Tylko jeszcze: `speeches.position = sejm_wystapienia._ord`

**Comment by kubazarz** [comment]
Done

**Comment by emendelski** [comment]
:+1:
