### ISSUE TITLE
me/skupstina: speeches: missing

### ISSUE THREAD

**Issue by KrzysztofMadejski** [emendelski/parldata-scrapers#9]
> All speeches are empty - without text and type.

One example here: 
http://api.parldata.eu/me/skupstina/speeches/54e72418273a391439e0dcbd

[Source PDF](http://www.skupstina.me/~skupcg/skupstina/cms/site_data/FONOGRAFSKI%20ZAPISI/5%20sj%20I%20red%20fono.pdf) should be read and divided into separate `speech` objects, one by each speaker with `type=speech` or other [Popolo classification types](http://www.popoloproject.com/specs/speech.html) if needed.

**Comment by KrzysztofMadejski** [comment]
Są już teksty, część podzielona i dobrze przypisani są mówcy. Niestety nie wszystkie teksty mówców są wyodrębnione. Jest też kilka innych błędów.

Np. dla: http://api.parldata.eu/me/skupstina/speeches?where={%22event_id%22:%2255030455273a39033bab54eb%22}
- [x] Zła kolejność. Powinna się zaczynać od "Poštovani poslanici 25. saziva Skupštine Crne Gore, otvaram Treću śednicu proljećnjeg ", a nie od "Prije nego dam riječ kolegi Mustafiću, da pojasnim u čemu " (kolejność jest regulowana przez `position`)
- [x] Brak wyodrębnienia tekstu wielu posłów. Dla position=1 w powyższym: 
  Prije nego dam riječ kolegi Mustafiću, da pojasnim u čemu je spor, pa ću dati riječ i kolegi Gošoviću i kolegi Damjanoviću. Ušli smo u raspravu, da to pojasnimo. Jedino što kolegi Daniloviću upućujem - ako je značajan manji broj, onda je pobjeda na predśedničkim izborima onaj koji dobije manje glasova, značajni pobjednik s manjim brojem. Jer, ne može biti veći broj značajan, manji može. Znači, pobjednik može biti i sa manjim brojem. Kolega Mustafiću, izvolite. Pokušavam da spustim tenzije. **SULJO MUSTAFIĆ**: Hvala Vam, predsjedniče
  
  SULJO MUSTAFIĆ powinien być wyodrębniony. Wydaje się to łatwe do regexpu, bo nowy mówca to zawsze nowa linia, drukowane litery i kropka na końcu. Uwaga na to, żeby regexpy działały na UTF-8!
- [x] Position=1 nie ma ustawionego creator_id. Tekst "PREDŚEDNIK" można pomijać, bo to chyba jakiś tytuł (może byc ich ogólnie więcej: marszałek, itp.). Ja budowałem sobie bazę posłów których znam w postaci "imię nazwisko" i sprawdzałem, czy jakikolwiek z "imie nazwisko" wystepuje w nazwie mówcy, żeby odfiltrować tytuły jak "predsednik". Ranko Kripkovic istnieje -> http://api.parldata.eu/me/skupstina/people?where={%22name%22:{%22$regex%22:%22RANKO%22,%22$options%22:%22i%22}}  
- [x] Jeżeli jakiś mówca nie istnieje to należy go dodać do bazy ustawiając: name, given_name, family_name, sources=przetwarzany pdf. Nie należy go przypisywać do żadnego organization, niech wisi luźno.

**Comment by kubazarz** [comment]
Czy możesz mi wysłać wynik działania pdftotext dla tego pliku z maszyny na której był odpalony scraper?  U mnie tekst zarówno przed jak i po podzieleniu na osoby jest we właściwej kolejności.

Co do łączenia osób z wypowiedziami, to mogą być czasami problemy bo zdarzają się literówki w stenogramach. Natomiast w tym przypadku jest to błąd.

**Comment by KrzysztofMadejski** [comment]
Chwila

**Comment by KrzysztofMadejski** [comment]
@krzysztofmadejski: podbić pdftotext na serwerze do  0.26.5

**Comment by KrzysztofMadejski** [comment]
Ustawiłem odpowiednią werjsę pdftotext i działa świetnie
